### ISSUE TITLE
Question on launching free_fleet_example_ros2

### ISSUE THREAD

**Issue by prashantking** [osrf/free_fleet#34]
i am trying to execute the tutorial from readme and while executing ros2 launch
ros2 launch free_fleet_examples_ros2 fake_server.launch.xml
i am getting this error.

[INFO] [launch]: All log files can be found below /home/user/.ros/log/2020-03-04-15-49-12-343851-user-Latitude-E5570-26745
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): The launch file may have a syntax error, or its format is unknown

unable to understand what is the issue.

**Comment by aaronchongth** [comment]
I have a hunch that this is due a missing dependency regarding `launch.xml`, could you try installing via `sudo apt install ros-eloquent-launch*`, and try again?

**Comment by prashantking** [comment]
yes it worked thankyou.

**Comment by rcywongaa** [comment]
It seems commit 1137e33bfa86639ea19b7536d665f07108c3f93f removes the instruction for installing `ros-eloquent-launch*` from the README which is still needed.
