### ISSUE TITLE
Installation troubles

### ISSUE THREAD

**Issue by machinedheart10** [osrf/free_fleet#36]
Hi, 

I was trying to set install the workspaces in ROS1 as well as in ROS2, however, there were issues regarding the dependencies on external packages. This could be avoided by possibly adding the following 

```
# install dependencies
rosdep update
rosdep install --from-paths src --ignore-src -y
```

after entering the workspace and sourcing the environment. 

For building the workspace in ROS 1, it could also be helpful to add in these 2 lines 

```
touch ~/client_ws/src/free_fleet/free_fleet_examples_ros2/CATKIN_IGNORE
touch ~/client_ws/src/free_fleet/free_fleet_server_ros2/CATKIN_IGNORE
```
so that we can build the ROS1 packages while ignoring the ROS2 packages.

**Comment by aaronchongth** [comment]
Thanks for catching the dependency issues! Patches are incoming.

For the warnings regarding ignoring ROS2 packages when building the ROS1 workspace, https://github.com/osrf/free_fleet/blob/master/free_fleet_server_ros2/CMakeLists.txt#L3-L5 was the alternate fix I put in place, which works but gives off a warning without building the package.

Adding `CATKIN_IGNORE` to `free_fleet_server_ros2` and `free_fleet_examples_ros2` will cause `colcon build` to ignore the packages as well when building the ROS2 workspace, you can try it out by calling

```
colcon build --packages-up-to free_fleet_server_ros2
colcon build --packages-up-to free_fleet_examples_ros2
```

**Comment by aaronchongth** [comment]
dependencies can now be installed using `rosdep`, with new instructions in the README.
