### ISSUE TITLE
Multi turtlebot3 obstacle avoidance issue

### ISSUE THREAD

**Issue by sinlam** [osrf/free_fleet#37]
Thanks for the example on how to launch multiple turtlebot3. I notice a issue with the multiple turtlebot3 in Gazebo and Rviz, now any of the turtlebot3 cannot avoid an obstacle when you add an object (e.g. beer can) in front of the turtlebot3, and move the turtlebot3 using Rviz. The turtlebot3 will hit the object and push it along. 
  For single turtlebot3, it will try to avoid the object and find another path. Is it possible to fix the obstacle avoidance issue in multiple turtlebot3? Thank you for any suggestion!

**Comment by aaronchongth** [comment]
Hello there! This issue is due to a missing prefix in the laser frame when setting up the local planner. This has been fixed in the referenced merge.

**Comment by sinlam** [comment]
Oh great. Thank you. I will try it soon!
