### ISSUE TITLE
1 package had stderr output: rmf_traffic

### ISSUE THREAD

**Issue by otomoov** [osrf/free_fleet#56]
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

<pre><font color="#8AE234"><b>oto@moov</b></font>:<font color="#729FCF"><b>~/server_ws</b></font>$ CXX=g++-8 colcon build --packages-select rmf_traffic
Starting &gt;&gt;&gt; rmf_traffic
--- stderr: rmf_traffic                               
<b>/home/oto/server_ws/src/rmf_core/rmf_traffic/src/rmf_traffic/schedule/Negotiation.cpp:</b> In static member function ‘<b>static rmf_utils::optional&lt;rmf_traffic::schedule::Negotiation&gt; rmf_traffic::schedule::Negotiation::make(std::shared_ptr&lt;const rmf_traffic::schedule::Viewer&gt;, std::vector&lt;long unsigned int&gt;)</b>’:
<b>/home/oto/server_ws/src/rmf_core/rmf_traffic/src/rmf_traffic/schedule/Negotiation.cpp:897:10:</b> <font color="#EF2929"><b>error: </b></font>could not convert ‘<b>negotiation</b>’ from ‘<b>rmf_traffic::schedule::Negotiation</b>’ to ‘<b>rmf_utils::optional&lt;rmf_traffic::schedule::Negotiation&gt; {aka std::optional&lt;rmf_traffic::schedule::Negotiation&gt;}</b>’
   return <font color="#EF2929"><b>negotiation</b></font>;
          <font color="#EF2929"><b>^~~~~~~~~~~</b></font>
make[2]: *** [CMakeFiles/rmf_traffic.dir/src/rmf_traffic/schedule/Negotiation.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/rmf_traffic.dir/all] Error 2
make: *** [all] Error 2
---
Failed   &lt;&lt;&lt; rmf_traffic [11.8s, exited with code 2]

Summary: 0 packages finished [12.0s]
  1 package failed: rmf_traffic
  1 package had stderr output: rmf_traffic</pre>

**Comment by aaronchongth** [comment]
Hello there, @otomoov ! 

Thanks for putting up the issue. There was a similar concern, https://github.com/osrf/free_fleet/issues/55, I would be patching in a fix for the documentation soon :D Stay tuned.

Meanwhile, let me know if you have any other questions.

**Comment by aaronchongth** [comment]
[This branch](https://github.com/osrf/free_fleet/pull/57) contains a number of fixes and changes to the documentation to work with rmf_core packages, however they target at Ubuntu 20.04, ROS 1 Noetic and ROS 2 Foxy. The branch will be merged soon after some more testing, but it is usable for the most part.

**Comment by otomoov** [comment]
> [This branch](https://github.com/osrf/free_fleet/pull/57) contains a number of fixes and changes to the documentation to work with rmf_core packages, however they target at Ubuntu 20.04, ROS 1 Noetic and ROS 2 Foxy. The branch will be merged soon after some more testing, but it is usable for the most part.

@aaronchongth 
Thank you. I was able to colcon build rmf_traffic on Ubuntu 20.04.1 LTS

**Comment by aaronchongth** [comment]
Reopening, due to the branch not merged yet. I will close it after it has been tested and merged.
