### ISSUE TITLE
Package 'ff_examples_ros2' not found

### ISSUE THREAD

**Issue by otomoov** [osrf/free_fleet#58]
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	        20.04
Codename:	focal

ROS1 noetic
ROS2 foxy
branch: fix/focal-docs

<pre><font color="#4E9A06"><b>oto@moov</b></font>:<font color="#3465A4"><b>~/server_ws</b></font>$ source ~/server_ws/install/setup.bash
ROS_DISTRO was set to &apos;foxy&apos; before. Please make sure that the environment does not mix paths from different distributions.
ROS_DISTRO was set to &apos;noetic&apos; before. Please make sure that the environment does not mix paths from different distributions.
<font color="#4E9A06"><b>oto@moov</b></font>:<font color="#3465A4"><b>~/server_ws</b></font>$ ros2 launch ff_examples_ros2 fake_server.launch.xml
Package &apos;ff_examples_ros2&apos; not found: &quot;package &apos;ff_examples_ros2&apos; not found, searching: [&apos;/home/oto/server_ws/install/rmf_traffic_msgs&apos;, &apos;/home/oto/server_ws/install/rmf_lift_msgs&apos;, &apos;/home/oto/server_ws/install/rmf_fleet_msgs&apos;, &apos;/home/oto/server_ws/install/rmf_door_msgs&apos;, &apos;/home/oto/server_ws/install/rmf_dispenser_msgs&apos;, &apos;/home/oto/server_ws/install/rmf_cmake_uncrustify&apos;, &apos;/home/oto/server_ws/install/ament_cmake_catch2&apos;, &apos;/home/oto/rmf_demos_ws/install/demos&apos;, &apos;/home/oto/rmf_demos_ws/install/visualizer&apos;, &apos;/home/oto/rmf_demos_ws/install/traffic_editor_assets&apos;, &apos;/home/oto/rmf_demos_ws/install/traffic_editor&apos;, &apos;/home/oto/rmf_demos_ws/install/test_maps&apos;, &apos;/home/oto/rmf_demos_ws/install/rviz2_plugin&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_workcell_msgs&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_schedule_visualizer&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_fleet_adapter&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_traffic_ros2&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_rviz_plugin&apos;, &apos;/home/oto/rmf_demos_ws/install/fleet_state_visualizer&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_traffic_msgs&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_demo_tasks&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_task_msgs&apos;, &apos;/home/oto/rmf_demos_ws/install/building_systems_visualizer&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_schedule_visualizer_msgs&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_demo_assets&apos;, &apos;/home/oto/rmf_demos_ws/install/building_ignition_plugins&apos;, &apos;/home/oto/rmf_demos_ws/install/building_gazebo_plugins&apos;, &apos;/home/oto/rmf_demos_ws/install/building_sim_common&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_lift_msgs&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_gazebo_plugins&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_ingestor_msgs&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_fleet_msgs&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_door_msgs&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_dispenser_msgs&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_demos_dashboard_resources&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_demo_maps&apos;, &apos;/home/oto/rmf_demos_ws/install/rmf_cmake_uncrustify&apos;, &apos;/home/oto/rmf_demos_ws/install/building_map_tools&apos;, &apos;/home/oto/rmf_demos_ws/install/building_map_msgs&apos;, &apos;/home/oto/rmf_demos_ws/install/ament_cmake_catch2&apos;, &apos;/opt/ros/foxy&apos;]&quot;
<font color="#4E9A06"><b>oto@moov</b></font>:<font color="#3465A4"><b>~</b></font></pre>

**Comment by aaronchongth** [comment]
Thank you for bringing it up, I have not been able to recreate it, unfortunately.

I see that you have both ROS versions sourced for your working terminal, could you try on a fresh terminal, make sure you don't have both workspaces sourced at the same time,

```
source ~/server_ws/install/setup.bash
ros2 launch ff_examples_ros2 fake_server.launch.xml
```

In the odd event that it was not built, you can try rebuilding the whole workspace from scratch,

```
cd ~/server_ws
rm -rf build install log
source /opt/ros/foxy/setup.bash
colcon build --cmake-args -DCMAKE_BUILD_TYPE=RELEASE --packages-up-to free_fleet free_fleet_server_ros2 ff_examples_ros2
```

Just as a sanity check, make sure you don't have both ROS versions sourced in your `.bashrc` file as well.

Let me know how it goes, cheers.

**Comment by otomoov** [comment]
Thank you. server_ws built with no issue. New issue,
<pre><font color="#4E9A06"><b>oto@moov</b></font>:<font color="#3465A4"><b>~/server_ws</b></font>$ ros2 launch ff_examples_ros2 fake_server.launch.xml
[INFO] [launch]: All log files can be found below /home/oto/.ros/log/2020-11-27-15-22-24-850433-moov-59337
[INFO] [launch]: Default logging verbosity is set to INFO
/opt/ros/foxy/lib/python3.8/site-packages/launch/frontend/expose.py:39: UserWarning: The parameter &apos;node_name&apos; is deprecated, use &apos;name&apos; instead
  return action_type(**kwargs)
Task exception was never retrieved
future: &lt;Task finished name=&apos;Task-2&apos; coro=&lt;LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:271&gt; exception=InvalidLaunchFileError(&apos;xml&apos;)&gt;
Traceback (most recent call last):
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py&quot;, line 53, in get_launch_description_from_any_launch_file
    return loader(launch_file_path)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/frontend_launch_file_utilities.py&quot;, line 35, in get_launch_description_from_frontend_launch_file
    return parser.parse_description(root_entity)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/frontend/parser.py&quot;, line 102, in parse_description
    actions = [self.parse_action(child) for child in entity.children]
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/frontend/parser.py&quot;, line 102, in &lt;listcomp&gt;
    actions = [self.parse_action(child) for child in entity.children]
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/frontend/parser.py&quot;, line 85, in parse_action
    return instantiate_action(entity, self)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/frontend/expose.py&quot;, line 39, in instantiate_action
    return action_type(**kwargs)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/node.py&quot;, line 174, in __init__
    raise RuntimeError(
RuntimeError: Passing both &apos;node_name&apos; and &apos;name&apos; parameters. Only use &apos;name&apos;.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py&quot;, line 273, in _process_one_event
    await self.__process_event(next_event)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py&quot;, line 293, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py&quot;, line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py&quot;, line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py&quot;, line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py&quot;, line 108, in visit
    return self.execute(context)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/include_launch_description.py&quot;, line 125, in execute
    launch_description = self.__launch_description_source.get_launch_description(context)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_source.py&quot;, line 84, in get_launch_description
    self._get_launch_description(self.__expanded_location)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_description_source.py&quot;, line 53, in _get_launch_description
    return get_launch_description_from_any_launch_file(location)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py&quot;, line 56, in get_launch_description_from_any_launch_file
    raise InvalidLaunchFileError(extension, likely_errors=exceptions)
launch.invalid_launch_file_error.InvalidLaunchFileError: Caught exception when trying to load file of format [xml]: Passing both &apos;node_name&apos; and &apos;name&apos; parameters. Only use &apos;name&apos;.
</pre>

**Comment by otomoov** [comment]
@aaronchongth thank you, server_ws built with no issue.
