### ISSUE TITLE
launch.invalid_launch_file_error.InvalidLaunchFileError:

### ISSUE THREAD

**Issue by otomoov** [osrf/free_fleet#59]
<pre><font color="#4E9A06"><b>oto@moov</b></font>:<font color="#3465A4"><b>~/server_ws</b></font>$ ros2 launch ff_examples_ros2 fake_server.launch.xml
[INFO] [launch]: All log files can be found below /home/oto/.ros/log/2020-11-27-15-22-24-850433-moov-59337
[INFO] [launch]: Default logging verbosity is set to INFO
/opt/ros/foxy/lib/python3.8/site-packages/launch/frontend/expose.py:39: UserWarning: The parameter &apos;node_name&apos; is deprecated, use &apos;name&apos; instead
  return action_type(**kwargs)
Task exception was never retrieved
future: &lt;Task finished name=&apos;Task-2&apos; coro=&lt;LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:271&gt; exception=InvalidLaunchFileError(&apos;xml&apos;)&gt;
Traceback (most recent call last):
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py&quot;, line 53, in get_launch_description_from_any_launch_file
    return loader(launch_file_path)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/frontend_launch_file_utilities.py&quot;, line 35, in get_launch_description_from_frontend_launch_file
    return parser.parse_description(root_entity)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/frontend/parser.py&quot;, line 102, in parse_description
    actions = [self.parse_action(child) for child in entity.children]
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/frontend/parser.py&quot;, line 102, in &lt;listcomp&gt;
    actions = [self.parse_action(child) for child in entity.children]
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/frontend/parser.py&quot;, line 85, in parse_action
    return instantiate_action(entity, self)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/frontend/expose.py&quot;, line 39, in instantiate_action
    return action_type(**kwargs)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/node.py&quot;, line 174, in __init__
    raise RuntimeError(
RuntimeError: Passing both &apos;node_name&apos; and &apos;name&apos; parameters. Only use &apos;name&apos;.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py&quot;, line 273, in _process_one_event
    await self.__process_event(next_event)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py&quot;, line 293, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py&quot;, line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py&quot;, line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py&quot;, line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py&quot;, line 108, in visit
    return self.execute(context)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/include_launch_description.py&quot;, line 125, in execute
    launch_description = self.__launch_description_source.get_launch_description(context)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_source.py&quot;, line 84, in get_launch_description
    self._get_launch_description(self.__expanded_location)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_description_source.py&quot;, line 53, in _get_launch_description
    return get_launch_description_from_any_launch_file(location)
  File &quot;/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py&quot;, line 56, in get_launch_description_from_any_launch_file
    raise InvalidLaunchFileError(extension, likely_errors=exceptions)
launch.invalid_launch_file_error.InvalidLaunchFileError: Caught exception when trying to load file of format [xml]: Passing both &apos;node_name&apos; and &apos;name&apos; parameters. Only use &apos;name&apos;.
</pre>

**Comment by aaronchongth** [comment]
Hello there @otomoov !

Could you make sure that you are using [this branch](https://github.com/osrf/free_fleet/pull/57)? This has been fixed here, https://github.com/osrf/free_fleet/blob/fix/focal-docs/ff_examples_ros2/launch/fake_server.launch.xml#L7 and https://github.com/osrf/free_fleet/blob/fix/focal-docs/ff_examples_ros2/launch/turtlebot3_world_ff.launch.xml#L7

As a sanity check, make sure you try a fresh build too,
```
cd ~/server_ws
rm -rf build install log
colcon build --cmake-args -DCMAKE_BUILD_TYPE=RELEASE --packages-up-to free_fleet free_fleet_server_ros2 ff_examples_ros2
```

**Comment by otomoov** [comment]
It is solved. Thank you!
I searched for <pre>turtlebot3_world_ff.launch.xml</pre> and in the file, I removed <pre>node-name="turtlebot3_fleet_server_node"</pre>

**Comment by aaronchongth** [comment]
Yes, please make sure to pull from the `fix/focal-docs` branch, it already has the changes you mentioned.
