### ISSUE TITLE
Comunication between ROS2 Foxy and ROS1 Melodic

### ISSUE THREAD

**Issue by Gryogor** [osrf/free_fleet#70]
Hello.
I have a question regarding free_fleet.
Is it possible to establish the communication between the ROS2 Foxy server on one computer and ROS1 Melodic client on other computer?

**Comment by aaronchongth** [comment]
Hello @Gryogor !

Yes, that is entirely possible. The middleware used between the server and the clients is [CycloneDDS](https://github.com/eclipse-cyclonedds/cyclonedds), which is agnostic to the ROS version.
